### ISSUE TITLE
Markdown issue in Lab 7

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#161]
https://microsoftlearning.github.io/DA-100-Analyzing-Data-with-Power-BI/Instructions/Labs/07-design-report-in-power-bi-desktop.html#task-1-get-started--sign-in

Issue seems to only be present on the GitHub pages site

![image](https://user-images.githubusercontent.com/1765732/145737433-460da9ca-3123-4026-98bc-dc06eac870f7.png)

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue while running the lab

**Comment by VitalyMCT** [comment]
@bpmoring There is what seems to be a generic (automated?) comment from @MOC-Labs-Review and it does not reflect the true state of the issue. I even have the link and screenshot and the issue is still very much there.

Can this please be adequately investigated & fixed?

**Comment by VitalyMCT** [comment]
It's not a blocker. When you investigate please check other labs as well, as the same Markdown issues are present in other places too.

**Comment by bpmoring** [comment]
All markdown issues have been addressed.

**Comment by VitalyMCT** [comment]
@bpmoring 

Issues still there ... for example, from the same lab:

![image](https://user-images.githubusercontent.com/1765732/148696870-f7f7de83-68d8-4db1-8de0-4abf45f54846.png)
